CREATE SCHEMA ENDERECO;

CREATE TABLE ENDERECO.TE_ENDERECO
(
    ID          SERIAL,
    DHCRIACAO   TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CEP         VARCHAR(10)                 NOT NULL,
    LOGRADOURO  VARCHAR(150)                NOT NULL,
    NUMERO      VARCHAR(100)                NOT NULL,
    COMPLEMENTO VARCHAR(80)                 NOT NULL,
    CIDADE      VARCHAR(150)                NOT NULL,
    ESTADO      VARCHAR(80)                 NOT NULL,

    CONSTRAINT PK_TE_ENDERECO PRIMARY KEY (ID)
);