CREATE SCHEMA CONTA;

--CONTA
CREATE TABLE CONTA.TE_CONTA
(
    ID             SERIAL,
    DHCRIACAO      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    EMAIL          VARCHAR(255) NOT NULL UNIQUE,
    SENHA          VARCHAR(150) NOT NULL,
    CPF            VARCHAR(15) NOT NULL UNIQUE,
    TELEFONE_DDD   SMALLINT NOT NULL,
    TELEFONE       BIGINT NOT NULL,
    ATIVA          BOOLEAN,
    CONTA_TIPO     VARCHAR(5) DEFAULT '000',
    ID_ENDERECO    BIGINT,

    CONSTRAINT PK_TE_CONTA PRIMARY KEY (ID),
    CONSTRAINT FK_TE_CONTA_ID_ENDERECO FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO.TE_ENDERECO (ID)
);

--TOKEN ATIVAÇÃO DE CONTAS
CREATE TABLE CONTA.TE_CONTA_CONFIRMACAO
(
    ID             SERIAL,
    TOKEN          VARCHAR(255) NOT NULL UNIQUE,
    DATA_EXPIRACAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    TENTATIVAS     INTEGER DEFAULT 0,
    ID_CONTA BIGINT,

    CONSTRAINT PK_TE_CONTA_CONFIRMACAO PRIMARY KEY (ID),
    CONSTRAINT FK_TE_CONTA_CONFIRMACAO_ID_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA.TE_CONTA (ID) ON DELETE CASCADE
);

--TOKEN REDEFINIÇÃO DE SENHA
CREATE TABLE CONTA.TE_CONTA_REDEFINICAO
(
    ID             SERIAL,
    DHCRIACAO      TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    TOKEN          VARCHAR(255) NOT NULL UNIQUE,
    DATA_EXPIRACAO TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    TENTATIVAS     INTEGER DEFAULT 0,
    ID_CONTA BIGINT,

    CONSTRAINT PK_TE_CONTA_REDEFINICAO PRIMARY KEY (ID),
    CONSTRAINT FK_TE_CONTA_REDEFINICAO_ID_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA.TE_CONTA (ID) ON DELETE CASCADE
);